az-bak.prod.surfshark.com
be-bru.prod.surfshark.com
ca-van.prod.surfshark.com
fr-par.prod.surfshark.com
de-fra.prod.surfshark.com
it-rom.prod.surfshark.com
nl-ams.prod.surfshark.com
es-mad.prod.surfshark.com
se-sto.prod.surfshark.com
ch-zur.prod.surfshark.com
uk-gla.prod.surfshark.com
us-nyc.prod.surfshark.com
